name: Jest
on: [push, pull_request]
jobs:
  build:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jest
        run: |
          npm install
          npm test
